app.name=VIPET
app.category=Education
app.author.name=Danijel Askov
app.author.email=danijel@askov.dev
app.version=1.0.0
app.reverseDomain=dev.askov.vipet
app.url=https://github.com/danijelaskov/vipet
app.description=Java desktop application for creating, simulating and analyzing queueing networks.
app.icon.windows=src/main/resources/dev/askov/vipet/img/app-icon.ico
app.icon.linux=src/main/resources/dev/askov/vipet/img/app-icon.png

java.version=21
javafx.version=21