# Window

window.icon=img/app-icon.png
window.maximized=true
window.size.width=800.0
window.size.height=300.0
# modena, caspian
window.theme=modena

# Locale

# sr, en
language=sr

# Content

# networks=

# Calculations

math.decimalDigits=4
math.groupingUsed=true
# UP, DOWN, CEILING, FLOOR, HALF_UP, HALF_DOWN, HALF_EVEN, UNNECESSARY
math.roundingMode=HALF_UP

# Random number generation

# Well512a, Well1024a, Well19937a, Well19937c, Well44497a, Well44497b, MersenneTwister
rng.type=Well512a
rng.seed=1000